/*
** textures.h for wolf3d in /home/benito/delivery/wolf3d/bonus
** 
** Made by Benoit Lormeau
** Login   <benoit.lormeau@epitech.eu>
** 
** Started on  Fri Dec 16 21:49:19 2016 Benoit Lormeau
** Last update Fri Dec 16 21:49:46 2016 Benoit Lormeau
*/

#ifndef TEXTURES_H_
# define TEXTURES_H_

# define WALL_UNDEF	"assets/texture/walls/portrait2.png"
# define WALL_A		"assets/texture/walls/greystone.png"
# define WALL_B		"assets/texture/walls/wood.png"
# define WALL_C		"assets/texture/walls/bluestone.png"
# define WALL_D		"assets/texture/walls/redbrick.png"
# define WALL_E		"assets/texture/walls/colorstone.png"
# define WALL_F		"assets/texture/walls/purplestone.png"
# define WALL_G		"assets/texture/walls/sandstone.png"
# define WALL_H		"assets/texture/walls/mossy.png"
# define WALL_I		"assets/texture/walls/statue.png"
# define WALL_J		"assets/texture/walls/flag_greystone.png"
# define WALL_K		"assets/texture/walls/flag_sandstone.png"
# define WALL_L		"assets/texture/walls/eagle.png"
# define WALL_M		"assets/texture/walls/portrait1.png"
# define WALL_N		"assets/texture/walls/portrait2.png"
# define WALL_O		""
# define WALL_P		""
# define WALL_Q		""
# define WALL_R		""
# define WALL_S		""
# define WALL_T		""
# define WALL_U		""
# define WALL_V		""
# define WALL_W		""
# define WALL_X		""
# define WALL_Y		""
# define WALL_Z		""

# define SPRITE_PILLAR	"assets/sprites/game_objects/pillar.png"
# define SPRITE_BARREL	"assets/sprites/game_objects/barrel.png"
# define SPRITE_LIGHT	"assets/sprites/game_objects/greenlight.png"

# define GUARD_00	"assets/sprites/guard/guard00.png"
# define GUARD_01	"assets/sprites/guard/guard01.png"
# define GUARD_02	"assets/sprites/guard/guard02.png"
# define GUARD_03	"assets/sprites/guard/guard03.png"
# define GUARD_04	"assets/sprites/guard/guard04.png"
# define GUARD_05	"assets/sprites/guard/guard05.png"
# define GUARD_06	"assets/sprites/guard/guard06.png"
# define GUARD_07	"assets/sprites/guard/guard07.png"
# define GUARD_10	"assets/sprites/guard/guard10.png"
# define GUARD_11	"assets/sprites/guard/guard11.png"
# define GUARD_12	"assets/sprites/guard/guard12.png"
# define GUARD_13	"assets/sprites/guard/guard13.png"
# define GUARD_14	"assets/sprites/guard/guard14.png"
# define GUARD_15	"assets/sprites/guard/guard15.png"
# define GUARD_16	"assets/sprites/guard/guard16.png"
# define GUARD_17	"assets/sprites/guard/guard17.png"
# define GUARD_20	"assets/sprites/guard/guard20.png"
# define GUARD_21	"assets/sprites/guard/guard21.png"
# define GUARD_22	"assets/sprites/guard/guard22.png"
# define GUARD_23	"assets/sprites/guard/guard23.png"
# define GUARD_24	"assets/sprites/guard/guard24.png"
# define GUARD_25	"assets/sprites/guard/guard25.png"
# define GUARD_26	"assets/sprites/guard/guard26.png"
# define GUARD_27	"assets/sprites/guard/guard27.png"
# define GUARD_30	"assets/sprites/guard/guard30.png"
# define GUARD_31	"assets/sprites/guard/guard31.png"
# define GUARD_32	"assets/sprites/guard/guard32.png"
# define GUARD_33	"assets/sprites/guard/guard33.png"
# define GUARD_34	"assets/sprites/guard/guard34.png"
# define GUARD_35	"assets/sprites/guard/guard35.png"
# define GUARD_36	"assets/sprites/guard/guard36.png"
# define GUARD_37	"assets/sprites/guard/guard37.png"
# define GUARD_40	"assets/sprites/guard/guard40.png"
# define GUARD_41	"assets/sprites/guard/guard41.png"
# define GUARD_42	"assets/sprites/guard/guard42.png"
# define GUARD_43	"assets/sprites/guard/guard43.png"
# define GUARD_44	"assets/sprites/guard/guard44.png"
# define GUARD_45	"assets/sprites/guard/guard45.png"
# define GUARD_46	"assets/sprites/guard/guard46.png"
# define GUARD_47	"assets/sprites/guard/guard47.png"
# define GUARD_50	"assets/sprites/guard/guard50.png"
# define GUARD_60	"assets/sprites/guard/guard60.png"
# define GUARD_70	"assets/sprites/guard/guard70.png"
# define GUARD_100	"assets/sprites/guard/guard100.png"
# define GUARD_200	"assets/sprites/guard/guard200.png"
# define GUARD_300	"assets/sprites/guard/guard300.png"
# define GUARD_400	"assets/sprites/guard/guard400.png"
# define GUARD_500	"assets/sprites/guard/guard500.png"

# define KNIFE_0	"assets/sprites/knife/0.png"
# define KNIFE_1	"assets/sprites/knife/1.png"
# define KNIFE_2	"assets/sprites/knife/2.png"
# define KNIFE_3	"assets/sprites/knife/3.png"
# define KNIFE_4	"assets/sprites/knife/4.png"

# define GUN_0		"assets/sprites/gun/0.png"
# define GUN_1		"assets/sprites/gun/1.png"
# define GUN_2		"assets/sprites/gun/2.png"
# define GUN_3		"assets/sprites/gun/3.png"
# define GUN_4		"assets/sprites/gun/4.png"

# define RIFLE_0	"assets/sprites/rifle/0.png"
# define RIFLE_1	"assets/sprites/rifle/1.png"
# define RIFLE_2	"assets/sprites/rifle/2.png"
# define RIFLE_3	"assets/sprites/rifle/3.png"
# define RIFLE_4	"assets/sprites/rifle/4.png"

# define GATLING_0	"assets/sprites/gatling/0.png"
# define GATLING_1	"assets/sprites/gatling/1.png"
# define GATLING_2	"assets/sprites/gatling/2.png"
# define GATLING_3	"assets/sprites/gatling/3.png"
# define GATLING_4	"assets/sprites/gatling/4.png"

#endif